name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity"
          plugin_lines: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: lowlighter

          plugins_errors_fatal: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0

          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs
          plugin_wakatime_limit: 4
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: rorepoid

          config_timezone: America/Lima
