name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity"
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: America/Lima
